src/dwz/persistence/beans/SysUserRole.java
package dwz.persistence.beans;

import org.apache.commons.lang.builder.EqualsBuilder;
import org.apache.commons.lang.builder.HashCodeBuilder;
import org.apache.commons.lang.builder.ToStringBuilder;
import org.apache.commons.lang.builder.ToStringStyle;

import dwz.dal.object.AbstractDO;

public class SysUserRole extends AbstractDO{
	/**
	 * 
	 */
	private static final long serialVersionUID = -8027428702874859293L;
	private Integer userId;
	private Integer roleId;

	public SysUserRole(){
	}

	public SysUserRole(Integer userId,Integer roleId){
		this.userId = userId;
		this.roleId = roleId;
	}

	public void setUserId(Integer value) {
		this.userId = value;
	}
	
	public Integer getUserId() {
		return this.userId;
	}
	public void setRoleId(Integer value) {
		this.roleId = value;
	}
	
	public Integer getRoleId() {
		return this.roleId;
	}

	public String toString() {
		return new ToStringBuilder(this,ToStringStyle.MULTI_LINE_STYLE)
			.append("UserId",getUserId())
			.append("RoleId",getRoleId())
			.toString();
	}
	
	public int hashCode() {
		return new HashCodeBuilder()
			.append(getUserId())
			.append(getRoleId())
			.toHashCode();
	}
	
	public boolean equals(Object obj) {
		if(obj instanceof SysUserRole == false) return false;
		if(this == obj) return true;
		SysUserRole other = (SysUserRole)obj;
		return new EqualsBuilder()
			.append(getUserId(),other.getUserId())
			.append(getRoleId(),other.getRoleId())
			.isEquals();
	}

	public Integer getId() {
		return null;
	}
}

src/dwz/web/NewsController.java
package dwz.web;

import java.util.List;

import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.stereotype.Controller;
import org.springframework.ui.Model;
import org.springframework.web.bind.annotation.PathVariable;
import org.springframework.web.bind.annotation.RequestMapping;

import dwz.business.info.News;
import dwz.business.info.NewsServiceMgr;
import dwz.business.info.NewsType;
import dwz.persistence.BaseConditionVO;

@Controller
@RequestMapping(value = "/news")
public class NewsController extends BaseController{

	@Autowired
	private NewsServiceMgr newsMgr;
	
	@RequestMapping("")
	public String list(BaseConditionVO vo, Model model) {
		List<News> newsList = newsMgr.searchNews(vo);
		int totalCount = newsMgr.searchNewsNum(vo);
		vo.setTotalCount(totalCount);
		
		model.addAttribute("newsTypes", NewsType.values());
		model.addAttribute("newsList", newsList);
		model.addAttribute("vo", vo);
		return "/news/list";
	}
	
	@RequestMapping("/view/{newsId}")
	public String view(@PathVariable("newsId") int newsId, Model model) {
		News news = newsMgr.getNews(newsId);

		model.addAttribute("newsTypes", NewsType.values());
		model.addAttribute("news", news);
		
		return "/news/view";
	}
	
}

src/dwz/web/management/IndexController.java
package dwz.web.management;

//import javax.inject.Inject;
import java.util.Date;

import org.springframework.stereotype.Controller;
import org.springframework.ui.Model;
import org.springframework.web.bind.annotation.ModelAttribute;
import org.springframework.web.bind.annotation.RequestMapping;

import dwz.web.BaseController;

@Controller("management.indexController")
@RequestMapping("/management")
public class IndexController extends BaseController{

	@RequestMapping("")
	public String index(Model model) {

		model.addAttribute("now", new Date());
		
		return "/management/index";
	}

	
}

src/dwz/web/management/NewsController.java
package dwz.web.management;

import java.util.List;

import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.stereotype.Controller;
import org.springframework.ui.Model;
import org.springframework.web.bind.annotation.PathVariable;
import org.springframework.web.bind.annotation.RequestMapping;
import org.springframework.web.bind.annotation.RequestMethod;
import org.springframework.web.servlet.ModelAndView;

import dwz.business.info.News;
import dwz.business.info.NewsServiceMgr;
import dwz.business.info.NewsType;
import dwz.persistence.BaseConditionVO;
import dwz.web.BaseController;

@Controller("management.newsController")
@RequestMapping(value = "/management/news")
public class NewsController extends BaseController {
	@Autowired
	private NewsServiceMgr newsMgr;
	
	@RequestMapping("")
	public String list(BaseConditionVO vo, Model model) {
		List<News> newsList = newsMgr.searchNews(vo);
		int totalCount = newsMgr.searchNewsNum(vo);
		vo.setTotalCount(totalCount);
		
		model.addAttribute("newsTypes", NewsType.values());
		model.addAttribute("newsList", newsList);
		model.addAttribute("vo", vo);
		return "/management/news/list";
	}
	
	@RequestMapping("/add")
	public String add(Model model) {
		model.addAttribute("newsTypes", NewsType.values());
		return "/management/news/add";
	}
	
	@RequestMapping("/edit/{newsId}")
	public String edit(@PathVariable("newsId") int newsId, Model model) {
		News news = newsMgr.getNews(newsId);

		model.addAttribute("newsTypes", NewsType.values());
		model.addAttribute("news", news);
		
		return "/management/news/edit";
	}
	
	@RequestMapping(value = "/insert", method = RequestMethod.POST)
	public ModelAndView insert(News news) {
		newsMgr.createNews(news);

		return ajaxDoneSuccess(getMessage("msg.operation.success"));
	}
	
	@RequestMapping(value = "/update", method = RequestMethod.POST)
	public ModelAndView update(News news) {
		newsMgr.updateNews(news);
		return ajaxDoneSuccess(getMessage("msg.operation.success"));
	}
	@RequestMapping("/publish/{newsId}")
	public ModelAndView publish(@PathVariable("newsId") int newsId) {
		newsMgr.publishNews(newsId);
		return ajaxDoneSuccess(getMessage("msg.operation.success"));
	}
	@RequestMapping("/disable/{newsId}")
	public ModelAndView disable(@PathVariable("newsId") int newsId) {
		newsMgr.disableNews(newsId);
		return ajaxDoneSuccess(getMessage("msg.operation.success"));
	}
	
	@RequestMapping("/delete/{newsId}")
	public ModelAndView delete(@PathVariable("newsId") int newsId) {
		newsMgr.removeNews(newsId);
		return ajaxDoneSuccess(getMessage("msg.operation.success"));
	}
}

src/dwz/web/management/UserController.java
package dwz.web.management;

import java.util.List;

import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.stereotype.Controller;
import org.springframework.ui.Model;
import org.springframework.web.bind.annotation.PathVariable;
import org.springframework.web.bind.annotation.RequestMapping;
import org.springframework.web.bind.annotation.RequestMethod;
import org.springframework.web.servlet.ModelAndView;

import dwz.framework.enums.Gender;
import dwz.framework.sys.exception.ServiceException;
import dwz.framework.user.User;
import dwz.framework.user.UserServiceMgr;
import dwz.framework.user.UserStatus;
import dwz.persistence.BaseConditionVO;
import dwz.web.BaseController;

@Controller("management.userController")
@RequestMapping(value="/management/user")
public class UserController extends BaseController{
	@Autowired
	private UserServiceMgr userMgr;

	@RequestMapping("")
	public String list(BaseConditionVO vo, Model model) {
		List<User> userList = userMgr.searchUser(vo);
		Integer totalCount = userMgr.searchUserNum(vo);
		
		model.addAttribute("userList", userList);
		model.addAttribute("totalCount", totalCount);
		model.addAttribute("userStatusList", UserStatus.values());
		model.addAttribute("pageSize", vo.getPageSize());

		return "/management/user/list";
	}
	
	@RequestMapping("/add")
	public String add(Model model) {
		model.addAttribute("genderList", Gender.values());
		return "/management/user/add";
	}
	
	@RequestMapping("/edit/{userId}")
	public String edit(@PathVariable("userId") int userId, Model model) {
		User user = userMgr.getUser(userId);

		model.addAttribute("vo", user);
		model.addAttribute("genderList", Gender.values());

		return "/management/user/edit";
	}
	
	@RequestMapping(value = "/insert", method = RequestMethod.POST)
	public ModelAndView insert(User user) {
		try {
			userMgr.addUser(user);
		} catch (ServiceException e) {
			return ajaxDoneError(e.getMessage());
		}

		return ajaxDoneSuccess(getMessage("msg.operation.success"));
	}
	
	@RequestMapping(value = "/update", method = RequestMethod.POST)
	public ModelAndView update(User user) {
		userMgr.updUser(user);
		return ajaxDoneSuccess(getMessage("msg.operation.success"));
	}
	
	@RequestMapping("/delete/{userId}")
	public ModelAndView delete(@PathVariable("userId") int userId) {

		userMgr.delUser(userId);

		return ajaxDoneSuccess(getMessage("msg.operation.success"));
	}
}

src/dwz/web/management/WebpageController.java
package dwz.web.management;

import java.util.List;

import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.stereotype.Controller;
import org.springframework.ui.Model;
import org.springframework.web.bind.annotation.PathVariable;
import org.springframework.web.bind.annotation.RequestMapping;
import org.springframework.web.bind.annotation.RequestMethod;
import org.springframework.web.servlet.ModelAndView;

import dwz.business.enums.PageTarget;
import dwz.business.website.Page;
import dwz.business.website.WebsiteServiceMgr;
import dwz.framework.sys.exception.ServiceException;
import dwz.web.BaseController;

@Controller("management.webpageController")
@RequestMapping(value = "/management/webpage")
public class WebpageController extends BaseController {
	@Autowired
	private WebsiteServiceMgr websiteMgr;

	@RequestMapping("/list")
	public String list(Model model) {
		List<Page> pages = websiteMgr.getPages();

		model.addAttribute("pages", pages);

		return "/management/webpage/list";
	}


	@RequestMapping("/add")
	public String add(Model model) {
		model.addAttribute("pageTargets", PageTarget.values());

		return "/management/webpage/add";
	}
	
	@RequestMapping("/edit/{pageId}")
	public String edit(@PathVariable("pageId") int pageId, Model model) {
		Page page = websiteMgr.getPage(pageId);

		model.addAttribute("page", page);
		model.addAttribute("pageTargets", PageTarget.values());
		
		return "/management/webpage/edit";
	}
	
	@RequestMapping(value = "/insert", method = RequestMethod.POST)
	public ModelAndView insert(Page page) {
		try {
			websiteMgr.createPage(page);
		} catch (ServiceException e) {
			return ajaxDoneError(e.getLocalizedMessage());
		}

		return ajaxDoneSuccess(getMessage("msg.operation.success"));
	}
	
	@RequestMapping(value = "/update", method = RequestMethod.POST)
	public ModelAndView update(Page page) {
		
		websiteMgr.updatePage(page);
		return ajaxDoneSuccess(getMessage("msg.operation.success"));
	}
	
	@RequestMapping("/delete/{pageId}")
	public ModelAndView delete(@PathVariable("pageId") int pageId) {
		websiteMgr.deletePage(pageId);
		return ajaxDoneSuccess(getMessage("msg.operation.success"));
	}
}

src/dwz/web/management/WebsiteController.java
package dwz.web.management;

import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.stereotype.Controller;
import org.springframework.ui.Model;
import org.springframework.web.bind.annotation.PathVariable;
import org.springframework.web.bind.annotation.RequestMapping;
import org.springframework.web.bind.annotation.RequestMethod;
import org.springframework.web.servlet.ModelAndView;

import dwz.business.website.Template;
import dwz.business.website.Website;
import dwz.business.website.WebsiteServiceMgr;
import dwz.framework.sys.exception.ServiceException;
import dwz.web.BaseController;

@Controller("management.websiteController")
@RequestMapping(value = "/management/website")
public class WebsiteController extends BaseController {
	@Autowired
	private WebsiteServiceMgr websiteMgr;

	@RequestMapping("/edit")
	public String edit(Model model) {
		model.addAttribute("website", websiteMgr.getWebsite());
		model.addAttribute("templates", websiteMgr.getTemplates());
		model.addAttribute("defaultTemplate", websiteMgr.getDefaultTemplate());

		return "/management/website/edit";
	}

	@RequestMapping(value = "/update", method = RequestMethod.POST)
	public ModelAndView save(Website website) {
		try {
			websiteMgr.saveWebsite(website);
		} catch (ServiceException e) {
			return ajaxDoneError(e.getLocalizedMessage());
		}
		return ajaxDoneSuccess(getMessage("msg.operation.success"));
	}
	
	@RequestMapping("/preview/{templateName}")
	public String preview(@PathVariable("templateName") String templateName, Model model) {
		Template template = websiteMgr.getTemplateByName(templateName);
		model.addAttribute("template", template);
		
		return "/management/website/preview";
	}
}

WebContent/WEB-INF/jsp/management/news/add.jsp
<%@ page contentType="text/html;charset=UTF-8" pageEncoding="UTF-8"%><%@ include file="/include.inc.jsp"%>
<h2 class="contentTitle">Add News</h2>

<form action="<c:url value='/management/news/insert?navTabId=newsLiNav&callbackType=closeCurrent'/>" method="post" class='required-validate pageForm' onsubmit="return iframeCallback(this, navTabAjaxDone);">

<div class="pageFormContent" layoutH="97">
	<div class="unit">
		<label>标题</label>
		<input type="text" name="title" class="textInput required" maxlength="200" size="100"/>
	</div>
	<div class="unit">
		<label>类型</label>
		<select class="required" name="type">
			<option value="">请选择</option>
			<c:forEach var="item" items="${newsTypes}">
			<option value="${item.id}">${item.name}</option>
			</c:forEach>
		</select>
	</div>
	<div class="unit">
		<label>内容</label>
		<textarea class="editor" name="content" rows="20" cols="80" tools="simple"></textarea>
	</div>
</div>
<div class="formBar">
	<ul>
		<li><div class="buttonActive"><div class="buttonContent"><button type="submit">保存</button></div></div></li>
		<li><div class="button"><div class="buttonContent"><button type="button" class="close">关闭</button></div></div></li>
	</ul>
</div>


</form>

WebContent/WEB-INF/jsp/management/news/edit.jsp
<%@ page contentType="text/html;charset=UTF-8" pageEncoding="UTF-8"%><%@ include file="/include.inc.jsp"%>
<h2 class="contentTitle">Edit News</h2>

<form action="<c:url value='/management/news/update?navTabId=newsLiNav&callbackType=closeCurrent'/>" method="post" class='required-validate pageForm' onsubmit="return iframeCallback(this, navTabAjaxDone);">
<input type="hidden" name="id" value="${news.id}" />

<div class="pageFormContent" layoutH="97">
	<div class="unit">
		<label>标题</label>
		<input type="text" name="title" value="${news.title}" class="textInput required" maxlength="200" size="100"/>
	</div>
	<div class="unit">
		<label>类型</label>
		<select class="required" name="type">
			<c:forEach var="item" items="${newsTypes}">
				<option value="${item.id}" ${news.type eq item ? 'selected="selected"':''} >${item.name}</option>
			</c:forEach>
		</select>
	</div>
	<div class="unit">
		<label>状态</label>
		${news.status.name}
	</div>
	<div class="unit">
		<label>内容</label>
		<textarea class="editor" name="content" rows="20" cols="80" tools="simple">${news.content}</textarea>
	</div>
</div>
<div class="formBar">
	<ul>
		<li><div class="buttonActive"><div class="buttonContent"><button type="submit">保存</button></div></div></li>
		<li><div class="button"><div class="buttonContent"><button type="button" class="close">关闭</button></div></div></li>
	</ul>
</div>

WebContent/WEB-INF/jsp/management/news/list.jsp
<%@ page contentType="text/html;charset=UTF-8" pageEncoding="UTF-8"%><%@ include file="/include.inc.jsp"%>
<c:import url="../_frag/pager/pagerForm.jsp"></c:import>

<form method="post" rel="pagerForm" action="<c:url value='/management/news'/>" onsubmit="return navTabSearch(this)">
<div class="pageHeader">
	<div class="searchBar">
		<ul class="searchContent">
			<li>
				<label>Keywords：</label>
				<input type="text" name="keywords" value="${param.keywords}"/>
			</li>
			<li>
				<label>Type：</label>
				<select name="type">
					<option value="">All</option>
					<c:forEach var="item" items="${newsTypes}">
					<option value="${item}" ${item.id eq param.newsType ? 'selected="selected"' : ''}>${item.name}</option>
					</c:forEach>
				</select>
			</li>
			
		</ul>
		<div class="subBar">
			<span style="margin-left: 5px; line-height: 25px; float: left">Matching Records Found: <strong>${vo.totalCount}</strong></span>
			<ul>						
				<li><div class="buttonActive"><div class="buttonContent"><button type="submit">Search</button></div></div></li>
			</ul>
		</div>
	</div>
</div>
</form>

<div class="pageContent">

	<div class="panelBar">
		<ul class="toolBar">
			<li><a class="add" target="navTab" rel="newsNav" href="<c:url value='/management/news/add'/>" title="Add News"><span>添加</span></a></li>
			<li><a class="edit" target="navTab" rel="newsNav" href="<c:url value='/management/news/edit/{slt_newsId}'/>" title="Edit News"><span>修改</span></a></li>
			<li><a class="delete" target="ajaxTodo" href="<c:url value='/management/news/delete/{slt_newsId}'/>" title="Are you sure remove?"><span>删除</span></a></li>
			<li class="line">line</li>
		</ul>
	</div>
	<table class="table" width="100%" layoutH="138">
		<thead>
			<tr>
				<th width="50px"></th>
				<th>标题</th>
				<th width="140px">创建时间</th>
				<th width="140px">修改时间</th>
				<th width="100px">类型</th>
				<th width="100px">状态</th>
				<th width="100px">操作</th>
			</tr>
		</thead>
		<tbody>
		<c:forEach var="item" items="${newsList}" varStatus="s">
			<tr target="slt_newsId" rel="${item.id }">
				<td>${s.index + 1}</td>
				<td>${item.title}</td>
				<td><fmt:formatDate value="${item.insertDate}" pattern="yyyy-MM-dd HH:mm:ss"/></td>
				<td><fmt:formatDate value="${item.updateDate}" pattern="yyyy-MM-dd HH:mm:ss"/></td>
				<td>${item.type.name}</td>
				<td>${item.status.name}</td>
				<td>
					<c:choose>
						<c:when test="${item.status eq 'PENDING' or item.status eq 'DISABLED'}">
							<a class="unit" target="ajaxTodo" href="/management/news/publish/${item.id}">Publish</a>
						</c:when>
						<c:when test="${item.status eq 'ACTIVE'}">
							<a class="unit" target="ajaxTodo" href="/management/news/disable/${item.id}">Disable</a>
						</c:when>
					</c:choose>
				</td>
			</tr>
		</c:forEach>
		</tbody>
	</table>

	<c:import url="../_frag/pager/panelBar.jsp"></c:import>
</div>